services:
  binancebot:
    build: .
    image: binancebot:latest
    ports:
      - "8080:8080"
      - "80:8080"
    volumes:
      - ./config/config.json:/config/config.json
      - ./user_data:/app/user_data
      - ./data:/app/data
    restart: unless-stopped
